In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print('done')

done

In [2]:
df = pd.read_csv('Credit Card Data.csv')

In [3]:
df.head()

,Client Number,Attrition Flag,Customer Age,Gender,Dependent Count,Education Level,Marital Status,Income Category,Card Category,Months on Book,...,Months Inactive (Last 12 Months),Contacts Count (Last 12 Months),Credit Limit,Total Revolving Balance,Average Open to Buy,Total Amount Change (Q4 vs Q1),Total Transaction Amount,Total Transaction Count,Total Transaction Count Change (Q4 vs Q1),Average Utilization Ratio
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000

In [4]:
df.isnull().sum()

Client Number                                0
Attrition Flag                               0
Customer Age                                 0
Gender                                       0
Dependent Count                              0
Education Level                              0
Marital Status                               0
Income Category                              0
Card Category                                0
Months on Book                               0
Total Relationship Count                     0
Months Inactive (Last 12 Months)             0
Contacts Count (Last 12 Months)              0
Credit Limit                                 0
Total Revolving Balance                      0
Average Open to Buy                          0
Total Amount Change (Q4 vs Q1)               0
Total Transaction Amount                     0
Total Transaction Count                      0
Total Transaction Count Change (Q4 vs Q1)    0
Average Utilization Ratio                    0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df = df.drop_duplicates()

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 21 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Client Number                              10127 non-null  int64
 1   Attrition Flag                             10127 non-null  object
 2   Customer Age                               10127 non-null  int64
 3   Gender                                     10127 non-null  object
 4   Dependent Count                            10127 non-null  int64
 5   Education Level                            10127 non-null  object
 6   Marital Status                             10127 non-null  object
 7   Income Category                            10127 non-null  object
 8   Card Category                              10127 non-null  object
 9   Months on Book                             10127 non-null  int64
 10  Total Relationship Count                   10127 non-null  int64
 11  Months Inactive (Last 12 Months)           10127 non-null  int64
 12  Contacts Count (Last 12 Months)            10127 non-null  int64
 13  Credit Limit                               10127 non-null  float64
 14  Total Revolving Balance                    10127 non-null  int64
 15  Average Open to Buy                        10127 non-null  float64
 16  Total Amount Change (Q4 vs Q1)             10127 non-null  float64
 17  Total Transaction Amount                   10127 non-null  int64
 18  Total Transaction Count                    10127 non-null  int64
 19  Total Transaction Count Change (Q4 vs Q1)  10127 non-null  float64
 20  Average Utilization Ratio                  10127 non-null  float64
dtypes: float64(5), int64(10), object(6)
memory usage: 1.6+ MB

In [9]:
df.head(11)

,Client Number,Attrition Flag,Customer Age,Gender,Dependent Count,Education Level,Marital Status,Income Category,Card Category,Months on Book,...,Months Inactive (Last 12 Months),Contacts Count (Last 12 Months),Credit Limit,Total Revolving Balance,Average Open to Buy,Total Amount Change (Q4 vs Q1),Total Transaction Amount,Total Transaction Count,Total Transaction Count Change (Q4 vs Q1),Average Utilization Ratio
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000
5,713061558,Existing Customer,44,M,2,Graduate,Married,$40K - $60K,Blue,36,...,1,2,4010.0,1247,2763.0,1.376,1088,24,0.846,0.311
6,810347208,Existing Customer,51,M,4,Unknown,Married,$120K +,Gold,46,...,1,3,34516.0,2264,32252.0,1.975,1330,31,0.722,0.066
7,818906208,Existing Customer,32,M,0,High School,Unknown,$60K - $80K,Silver,27,...,2,2,29081.0,1396,27685.0,2.204,1538,36,0.714,0.048
8,710930508,Existing Customer,37,M,3,Uneducated,Single,$60K - $80K,Blue,36,...,2,0,22352.0,2517,19835.0,3.355,1350,24,1.182,0.113
9,719661558,Existing Customer,48,M,2,Graduate,Single,$80K - $120K,Blue,36,...,3,3,11656.0,1677,9979.0,1.524,1441,32,0.882,0.144
10,708790833,Existing Customer,42,M,5,Uneducated,Unknown,$120K +,Blue,31,...,3,2,6748.0,1467,5281.0,0.831,1201,42,0.680,0.217

In [10]:
df['Gender'] = df['Gender'].replace({'M': 'Male', 'F': 'Female'})

In [11]:
df.head(11)

,Client Number,Attrition Flag,Customer Age,Gender,Dependent Count,Education Level,Marital Status,Income Category,Card Category,Months on Book,...,Months Inactive (Last 12 Months),Contacts Count (Last 12 Months),Credit Limit,Total Revolving Balance,Average Open to Buy,Total Amount Change (Q4 vs Q1),Total Transaction Amount,Total Transaction Count,Total Transaction Count Change (Q4 vs Q1),Average Utilization Ratio
0,768805383,Existing Customer,45,Male,3,High School,Married,$60K - $80K,Blue,39,...,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,818770008,Existing Customer,49,Female,5,Graduate,Single,Less than $40K,Blue,44,...,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,713982108,Existing Customer,51,Male,3,Graduate,Married,$80K - $120K,Blue,36,...,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,769911858,Existing Customer,40,Female,4,High School,Unknown,Less than $40K,Blue,34,...,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,709106358,Existing Customer,40,Male,3,Uneducated,Married,$60K - $80K,Blue,21,...,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000
5,713061558,Existing Customer,44,Male,2,Graduate,Married,$40K - $60K,Blue,36,...,1,2,4010.0,1247,2763.0,1.376,1088,24,0.846,0.311
6,810347208,Existing Customer,51,Male,4,Unknown,Married,$120K +,Gold,46,...,1,3,34516.0,2264,32252.0,1.975,1330,31,0.722,0.066
7,818906208,Existing Customer,32,Male,0,High School,Unknown,$60K - $80K,Silver,27,...,2,2,29081.0,1396,27685.0,2.204,1538,36,0.714,0.048
8,710930508,Existing Customer,37,Male,3,Uneducated,Single,$60K - $80K,Blue,36,...,2,0,22352.0,2517,19835.0,3.355,1350,24,1.182,0.113
9,719661558,Existing Customer,48,Male,2,Graduate,Single,$80K - $120K,Blue,36,...,3,3,11656.0,1677,9979.0,1.524,1441,32,0.882,0.144
10,708790833,Existing Customer,42,Male,5,Uneducated,Unknown,$120K +,Blue,31,...,3,2,6748.0,1467,5281.0,0.831,1201,42,0.680,0.217

In [15]:
print(df.columns)

Index(['Client Number', 'Attrition Flag', 'Customer Age', 'Gender',
       'Dependent Count', 'Education Level', 'Marital Status',
       'Income Category', 'Card Category', 'Months on Book',
       'Total Relationship Count', 'Months Inactive (Last 12 Months)',
       'Contacts Count (Last 12 Months)', 'Credit Limit',
       'Total Revolving Balance', 'Average Open to Buy',
       'Total Amount Change (Q4 vs Q1)', 'Total Transaction Amount',
       'Total Transaction Count', 'Total Transaction Count Change (Q4 vs Q1)',
       'Average Utilization Ratio'],
      dtype='object')

In [16]:
print(df['Marital Status'].unique())
print(df['Education Level'].unique())

['Married' 'Single' 'Unknown' 'Divorced']
['High School' 'Graduate' 'Uneducated' 'Unknown' 'College' 'Post-Graduate'
 'Doctorate']

In [17]:
print(df.dtypes)

Client Number                                  int64
Attrition Flag                                object
Customer Age                                   int64
Gender                                        object
Dependent Count                                int64
Education Level                               object
Marital Status                                object
Income Category                               object
Card Category                                 object
Months on Book                                 int64
Total Relationship Count                       int64
Months Inactive (Last 12 Months)               int64
Contacts Count (Last 12 Months)                int64
Credit Limit                                 float64
Total Revolving Balance                        int64
Average Open to Buy                          float64
Total Amount Change (Q4 vs Q1)               float64
Total Transaction Amount                       int64
Total Transaction Count                        int64
Total Transaction Count Change (Q4 vs Q1)    float64
Average Utilization Ratio                    float64
dtype: object

In [19]:
import pandas as pd

# 1. Age Groups
bins = [20, 30, 45, 60, 100]
labels = ['Young Adult', 'Adult', 'Middle-Aged', 'Senior']
df['Age_Group'] = pd.cut(df['Customer Age'], bins=bins, labels=labels)

# 2. Tenure in Years
df['Tenure_Years'] = df['Months on Book'] / 12

# 3. Average Transaction Value
df['Avg_Transaction_Value'] = df['Total Transaction Amount'] / df['Total Transaction Count']

# 4. Credit Utilization Tier
df['Utilization_Tier'] = pd.cut(
    df['Average Utilization Ratio'], 
    bins=[-0.1, 0.3, 0.7, 1.0], 
    labels=['Low', 'Moderate', 'High']
)

In [21]:
print(df[['Customer Age', 'Age_Group', 'Months on Book', 'Tenure_Years']].head(9))

   Customer Age    Age_Group  Months on Book  Tenure_Years
0            45        Adult              39      3.250000
1            49  Middle-Aged              44      3.666667
2            51  Middle-Aged              36      3.000000
3            40        Adult              34      2.833333
4            40        Adult              21      1.750000
5            44        Adult              36      3.000000
6            51  Middle-Aged              46      3.833333
7            32        Adult              27      2.250000
8            37        Adult              36      3.000000

In [22]:
df.head(9)

,Client Number,Attrition Flag,Customer Age,Gender,Dependent Count,Education Level,Marital Status,Income Category,Card Category,Months on Book,...,Average Open to Buy,Total Amount Change (Q4 vs Q1),Total Transaction Amount,Total Transaction Count,Total Transaction Count Change (Q4 vs Q1),Average Utilization Ratio,Age_Group,Tenure_Years,Avg_Transaction_Value,Utilization_Tier
0,768805383,Existing Customer,45,Male,3,High School,Married,$60K - $80K,Blue,39,...,11914.0,1.335,1144,42,1.625,0.061,Adult,3.250000,27.238095,Low
1,818770008,Existing Customer,49,Female,5,Graduate,Single,Less than $40K,Blue,44,...,7392.0,1.541,1291,33,3.714,0.105,Middle-Aged,3.666667,39.121212,Low
2,713982108,Existing Customer,51,Male,3,Graduate,Married,$80K - $120K,Blue,36,...,3418.0,2.594,1887,20,2.333,0.000,Middle-Aged,3.000000,94.350000,Low
3,769911858,Existing Customer,40,Female,4,High School,Unknown,Less than $40K,Blue,34,...,796.0,1.405,1171,20,2.333,0.760,Adult,2.833333,58.550000,High
4,709106358,Existing Customer,40,Male,3,Uneducated,Married,$60K - $80K,Blue,21,...,4716.0,2.175,816,28,2.500,0.000,Adult,1.750000,29.142857,Low
5,713061558,Existing Customer,44,Male,2,Graduate,Married,$40K - $60K,Blue,36,...,2763.0,1.376,1088,24,0.846,0.311,Adult,3.000000,45.333333,Moderate
6,810347208,Existing Customer,51,Male,4,Unknown,Married,$120K +,Gold,46,...,32252.0,1.975,1330,31,0.722,0.066,Middle-Aged,3.833333,42.903226,Low
7,818906208,Existing Customer,32,Male,0,High School,Unknown,$60K - $80K,Silver,27,...,27685.0,2.204,1538,36,0.714,0.048,Adult,2.250000,42.722222,Low
8,710930508,Existing Customer,37,Male,3,Uneducated,Single,$60K - $80K,Blue,36,...,19835.0,3.355,1350,24,1.182,0.113,Adult,3.000000,56.250000,Low

In [23]:
df = df.rename(columns={
    'Age_Group': 'Age Group',
    'Tenure_Years': 'Tenure Years',
    'Avg_Transaction_Value': 'Avg Transaction Value',
    'Utilization_Tier': 'Utilization Tier'
})

In [24]:
df.head(9)

,Client Number,Attrition Flag,Customer Age,Gender,Dependent Count,Education Level,Marital Status,Income Category,Card Category,Months on Book,...,Average Open to Buy,Total Amount Change (Q4 vs Q1),Total Transaction Amount,Total Transaction Count,Total Transaction Count Change (Q4 vs Q1),Average Utilization Ratio,Age Group,Tenure Years,Avg Transaction Value,Utilization Tier
0,768805383,Existing Customer,45,Male,3,High School,Married,$60K - $80K,Blue,39,...,11914.0,1.335,1144,42,1.625,0.061,Adult,3.250000,27.238095,Low
1,818770008,Existing Customer,49,Female,5,Graduate,Single,Less than $40K,Blue,44,...,7392.0,1.541,1291,33,3.714,0.105,Middle-Aged,3.666667,39.121212,Low
2,713982108,Existing Customer,51,Male,3,Graduate,Married,$80K - $120K,Blue,36,...,3418.0,2.594,1887,20,2.333,0.000,Middle-Aged,3.000000,94.350000,Low
3,769911858,Existing Customer,40,Female,4,High School,Unknown,Less than $40K,Blue,34,...,796.0,1.405,1171,20,2.333,0.760,Adult,2.833333,58.550000,High
4,709106358,Existing Customer,40,Male,3,Uneducated,Married,$60K - $80K,Blue,21,...,4716.0,2.175,816,28,2.500,0.000,Adult,1.750000,29.142857,Low
5,713061558,Existing Customer,44,Male,2,Graduate,Married,$40K - $60K,Blue,36,...,2763.0,1.376,1088,24,0.846,0.311,Adult,3.000000,45.333333,Moderate
6,810347208,Existing Customer,51,Male,4,Unknown,Married,$120K +,Gold,46,...,32252.0,1.975,1330,31,0.722,0.066,Middle-Aged,3.833333,42.903226,Low
7,818906208,Existing Customer,32,Male,0,High School,Unknown,$60K - $80K,Silver,27,...,27685.0,2.204,1538,36,0.714,0.048,Adult,2.250000,42.722222,Low
8,710930508,Existing Customer,37,Male,3,Uneducated,Single,$60K - $80K,Blue,36,...,19835.0,3.355,1350,24,1.182,0.113,Adult,3.000000,56.250000,Low

In [25]:
df['Tenure Years'] = df['Tenure Years'].round(2)
df['Avg Transaction Value'] = df['Avg Transaction Value'].round(2)

In [26]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [27]:
df.head(9)

,Client Number,Attrition Flag,Customer Age,Gender,Dependent Count,Education Level,Marital Status,Income Category,Card Category,Months on Book,...,Average Open to Buy,Total Amount Change (Q4 vs Q1),Total Transaction Amount,Total Transaction Count,Total Transaction Count Change (Q4 vs Q1),Average Utilization Ratio,Age Group,Tenure Years,Avg Transaction Value,Utilization Tier
0,768805383,Existing Customer,45,Male,3,High School,Married,$60K - $80K,Blue,39,...,11914.00,1.33,1144,42,1.62,0.06,Adult,3.25,27.24,Low
1,818770008,Existing Customer,49,Female,5,Graduate,Single,Less than $40K,Blue,44,...,7392.00,1.54,1291,33,3.71,0.10,Middle-Aged,3.67,39.12,Low
2,713982108,Existing Customer,51,Male,3,Graduate,Married,$80K - $120K,Blue,36,...,3418.00,2.59,1887,20,2.33,0.00,Middle-Aged,3.00,94.35,Low
3,769911858,Existing Customer,40,Female,4,High School,Unknown,Less than $40K,Blue,34,...,796.00,1.41,1171,20,2.33,0.76,Adult,2.83,58.55,High
4,709106358,Existing Customer,40,Male,3,Uneducated,Married,$60K - $80K,Blue,21,...,4716.00,2.17,816,28,2.50,0.00,Adult,1.75,29.14,Low
5,713061558,Existing Customer,44,Male,2,Graduate,Married,$40K - $60K,Blue,36,...,2763.00,1.38,1088,24,0.85,0.31,Adult,3.00,45.33,Moderate
6,810347208,Existing Customer,51,Male,4,Unknown,Married,$120K +,Gold,46,...,32252.00,1.98,1330,31,0.72,0.07,Middle-Aged,3.83,42.90,Low
7,818906208,Existing Customer,32,Male,0,High School,Unknown,$60K - $80K,Silver,27,...,27685.00,2.20,1538,36,0.71,0.05,Adult,2.25,42.72,Low
8,710930508,Existing Customer,37,Male,3,Uneducated,Single,$60K - $80K,Blue,36,...,19835.00,3.35,1350,24,1.18,0.11,Adult,3.00,56.25,Low

In [29]:
df.to_csv('CreditCardDataCleaned.csv', index=False)